### ISSUE TITLE
Minified React Error w/ Next.js and Vercel

### ISSUE THREAD

**Issue by harshhhdev** [nihgwu/react-runner#146]
I've deployed `react-runner` into production in Vercel using Next.js, but for some reason I get this minified react error logged into the console and the code editor doesn't run properly as the output is blank.

```
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lg (react-dom.production.min.js:132:269)
    at i (react-dom.production.min.js:294:336)
    at oD (react-dom.production.min.js:281:375)
    at react-dom.production.min.js:281:315
    at oO (react-dom.production.min.js:281:315)
    at ox (react-dom.production.min.js:269:193)
    at x (scheduler.production.min.js:14:181)
    at MessagePort.T (scheduler.production.min.js:15:101)
```

For context, this works perfectly fine in dev. I'll attach screenshots below. The first is in development, the second in production:

![screenshot in dev, with a button](https://user-images.githubusercontent.com/69592270/209872803-2b4cca6f-ffaf-4b52-b531-cbf6882d6e6a.png)
![screenshot in product, with no button](https://user-images.githubusercontent.com/69592270/209872806-52fd910c-dba2-42ce-bbda-46b7e1465b55.png)

**Comment by nihgwu** [comment]
Ihttps://reactjs.org/docs/error-decoder.html/?invariant=418 please check what cause the mismatch during hydration, I guess you should get some errors in your console in dev env as well

**Comment by harshhhdev** [comment]
Hey @nihgwu, 
While running my application in development, there are no errors logged into the console. It's only in production, and I've linked the error above.

You can check out my application in production at [lab.hxrsh.in/posts/toasts](https://lab.hxrsh.in/posts/toasts) for more information if that's helpful.

**Comment by nihgwu** [comment]
@harshhhdev still have no idea, but this error https://reactjs.org/docs/error-decoder.html/?invariant=423 looks weird because there is ErrorBoundary in react-runner

**Comment by harshhhdev** [comment]
Would you have any ideas on how to go about fixing it @nihgwu? Any other information I can provide?

**Comment by nihgwu** [comment]
@harshhhdev If you think it's fine then I'm happy to debug with the source code

**Comment by harshhhdev** [comment]
Hey, @nihgwu 
Sorry for the delay. I've added you onto it. You'll need to accept the invite in your email. 

You can find it at [harshhhdev/experiments](https://github.com/harshhhdev/experiments).

**Comment by nihgwu** [comment]
@harshhhdev looks more like a bug in Next

this will trigger the error
```
const Editor = () => {
  return (
    <div>
      <Runner code={initial} />
    </div>
  );
};

export default function Page() {
  return <Editor />;
}
```

while this doesn't
```
const Editor = () => {
  return (
    <Runner code={initial} />
  );
};

export default function Page() {
  return <Editor />;
}
```
